// Generated by scripts/generate-analytics.ts. Do not edit by hand.

export const ANALYTICS_EVENTS = {
  "ACCOUNT_DELETE_PROMPT": "account_delete_prompt",
  "ACCOUNT_DELETE_RESULT": "account_delete_result",
  "ALTERNATE_SELECTED": "alternate_selected",
  "CAMERA_PERMISSION_RESULT": "camera_permission_result",
  "CARE_LOG_RESULT": "care_log_result",
  "CARE_REMINDER_TOGGLE": "care_reminder_toggle",
  "DIAGNOSE_RESULT": "diagnose_result",
  "DIAGNOSIS_ATTACH_SELECT": "diagnosis_attach_select",
  "DIAGNOSIS_EXPAND": "diagnosis_expand",
  "DIAGNOSIS_SAVE_RESULT": "diagnosis_save_result",
  "DEEP_LINK_OPEN": "deep_link_open",
  "FIRST_PLANT_SAVED": "first_plant_saved",
  "FREE_LIMIT_HIT": "free_limit_hit",
  "FROST_ALERT_TOGGLE": "frost_alert_toggle",
  "GROWTH_PHOTO_ADD": "growth_photo_add",
  "IDENTIFY_RESULT": "identify_result",
  "LEGAL_LINK_TAP": "legal_link_tap",
  "LIBRARY_PERMISSION_RESULT": "library_permission_result",
  "MANAGE_SUBSCRIPTION_LINK": "manage_subscription_link",
  "OFFER_CODE_REDEMPTION": "offer_code_redemption",
  "ONBOARDING_COMPLETE": "onboarding_complete",
  "ONBOARDING_SKIP": "onboarding_skip",
  "NOTIFICATION_OPEN": "notification_open",
  "PAYWALL_VIEW": "paywall_view",
  "PHOTO_CAPTURE": "photo_capture",
  "PHOTO_PICK": "photo_pick",
  "PLAN_SELECT": "plan_select",
  "PLANT_DELETE_PROMPT": "plant_delete_prompt",
  "PLANT_DELETE_RESULT": "plant_delete_result",
  "PLANT_PHOTO_REPLACEMENT": "plant_photo_replacement",
  "PLANT_SAVE_RESULT": "plant_save_result",
  "PLANT_UPDATE_RESULT": "plant_update_result",
  "PREMIUM_CTA": "premium_cta",
  "PURCHASE_RESULT": "purchase_result",
  "PURCHASE_START": "purchase_start",
  "RESTORE_RESULT": "restore_result",
  "RESTORE_START": "restore_start",
  "SCAN_AGAIN": "scan_again",
  "SCAN_MODE_CHANGE": "scan_mode_change",
  "SCAN_SUBMIT": "scan_submit",
  "SIGN_IN_CANCEL": "sign_in_cancel",
  "SIGN_IN_FAILURE": "sign_in_failure",
  "PERMANENT_ACCOUNT_CREATED": "permanent_account_created",
  "RETURNING_SIGN_IN": "returning_sign_in",
  "SIGN_IN_RESULT": "sign_in_result",
  "SIGN_IN_TAP": "sign_in_tap",
  "SIGN_OUT": "sign_out",
  "TASK_INTERVAL_UPDATE": "task_interval_update",
  "TASK_TOGGLE": "task_toggle",
  "TODAY_TASK_COMPLETE": "today_task_complete",
  "UI_TAP": "ui_tap",
  "WEATHER_LOCATION_REMOVE": "weather_location_remove",
  "WEATHER_LOCATION_SET": "weather_location_set",
  "WEATHER_TIP_ACTION": "weather_tip_action"
} as const;

export const ANALYTICS_TAPS = {
  "LEGAL_EULA_LINK": "legal_eula_link",
  "LEGAL_PRIVACY_LINK": "legal_privacy_link",
  "LEGAL_TERMS_LINK": "legal_terms_link",
  "PREMIUM_MANAGE_SUBSCRIPTION": "premium_manage_subscription",
  "PROFILE_PRIVACY_CHOICES": "profile_privacy_choices",
  "SIGN_IN_APPLE_BUTTON": "sign_in_apple_button",
  "SIGN_IN_GOOGLE_BUTTON": "sign_in_google_button"
} as const;

export const ANALYTICS_USER_PROPERTY_KEYS = [
  "auth_provider",
  "care_reminders_enabled",
  "onboarding_status",
  "plant_count_bucket",
  "platform",
  "premium_status",
  "weather_location_source"
] as const;

export const GENERATED_EVENT_DEFINITIONS = {
  "account_delete_prompt": {
    "description": "Records the Fernly account delete prompt product milestone.",
    "trigger": "Emitted by the existing account delete prompt application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "account_delete_result": {
    "description": "Records the Fernly account delete result product milestone.",
    "trigger": "Emitted by the existing account delete result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "alternate_selected": {
    "description": "Records the Fernly alternate selected product milestone.",
    "trigger": "Emitted by the existing alternate selected application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "alternate_rank": "number",
      "selected": "boolean"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "camera_permission_result": {
    "description": "Records the Fernly camera permission result product milestone.",
    "trigger": "Emitted by the existing camera permission result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "result": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "care_log_result": {
    "description": "Records the Fernly care log result product milestone.",
    "trigger": "Emitted by the existing care log result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string",
      "type": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "care_reminder_toggle": {
    "description": "Records the Fernly care reminder toggle product milestone.",
    "trigger": "Emitted by the existing care reminder toggle application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "enabled": "boolean",
      "result": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "diagnose_result": {
    "description": "Records the Fernly diagnose result product milestone.",
    "trigger": "Emitted by the existing diagnose result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string",
      "stage": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "diagnosis_attach_select": {
    "description": "Records the Fernly diagnosis attach select product milestone.",
    "trigger": "Emitted by the existing diagnosis attach select application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "diagnosis_expand": {
    "description": "Records the Fernly diagnosis expand product milestone.",
    "trigger": "Emitted by the existing diagnosis expand application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "expanded": "boolean"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "diagnosis_save_result": {
    "description": "Records the Fernly diagnosis save result product milestone.",
    "trigger": "Emitted by the existing diagnosis save result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "attached_to_plant": "boolean",
      "reason": "string",
      "result": "string",
      "target": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "deep_link_open": {
    "description": "Records the Fernly deep link open product milestone.",
    "trigger": "Emitted by the existing deep link open application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "deferred": "boolean",
      "destination": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "first_plant_saved": {
    "description": "Records the Fernly first plant saved product milestone.",
    "trigger": "Emitted by the existing first plant saved application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "high",
    "partnerPostbackEligible": true
  },
  "free_limit_hit": {
    "description": "Records the Fernly free limit hit product milestone.",
    "trigger": "Emitted by the existing free limit hit application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "mode": "string",
      "reason": "string",
      "stage": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "frost_alert_toggle": {
    "description": "Records the Fernly frost alert toggle product milestone.",
    "trigger": "Emitted by the existing frost alert toggle application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "enabled": "boolean",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "growth_photo_add": {
    "description": "Records the Fernly growth photo add product milestone.",
    "trigger": "Emitted by the existing growth photo add application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "identify_result": {
    "description": "Records the Fernly identify result product milestone.",
    "trigger": "Emitted by the existing identify result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "has_species_profile": "boolean",
      "reason": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "appsFlyerAlias": "af_search",
    "aliasWhen": {
      "parameter": "result",
      "equals": "success"
    },
    "conversionPriority": "high",
    "partnerPostbackEligible": true
  },
  "legal_link_tap": {
    "description": "Records the Fernly legal link tap product milestone.",
    "trigger": "Emitted by the existing legal link tap application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "surface": "string",
      "target": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "library_permission_result": {
    "description": "Records the Fernly library permission result product milestone.",
    "trigger": "Emitted by the existing library permission result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "result": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "manage_subscription_link": {
    "description": "Records the Fernly manage subscription link product milestone.",
    "trigger": "Emitted by the existing manage subscription link application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "offer_code_redemption": {
    "description": "Records the Fernly offer code redemption product milestone.",
    "trigger": "Emitted by the existing offer code redemption application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "result": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "onboarding_complete": {
    "description": "Records the Fernly onboarding complete product milestone.",
    "trigger": "Emitted by the existing onboarding complete application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "method": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "appsFlyerAlias": "af_tutorial_completion",
    "conversionPriority": "high",
    "partnerPostbackEligible": true
  },
  "onboarding_skip": {
    "description": "Records the Fernly onboarding skip product milestone.",
    "trigger": "Emitted by the existing onboarding skip application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {},
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "notification_open": {
    "description": "Records the Fernly notification open product milestone.",
    "trigger": "Emitted by the existing notification open application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "destination": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "appsFlyerAlias": "af_opened_from_push_notification",
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "paywall_view": {
    "description": "Records the Fernly paywall view product milestone.",
    "trigger": "Emitted by the existing paywall view application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "premium_status": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "appsFlyerAlias": "af_content_view",
    "conversionPriority": "high",
    "partnerPostbackEligible": true
  },
  "photo_capture": {
    "description": "Records the Fernly photo capture product milestone.",
    "trigger": "Emitted by the existing photo capture application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "mode": "string",
      "reason": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "photo_pick": {
    "description": "Records the Fernly photo pick product milestone.",
    "trigger": "Emitted by the existing photo pick application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "mode": "string",
      "reason": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "plan_select": {
    "description": "Records the Fernly plan select product milestone.",
    "trigger": "Emitted by the existing plan select application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "plan": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "plant_delete_prompt": {
    "description": "Records the Fernly plant delete prompt product milestone.",
    "trigger": "Emitted by the existing plant delete prompt application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "plant_delete_result": {
    "description": "Records the Fernly plant delete result product milestone.",
    "trigger": "Emitted by the existing plant delete result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "plant_photo_replacement": {
    "description": "Records the Fernly plant photo replacement product milestone.",
    "trigger": "Emitted by the existing plant photo replacement application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string",
      "source": "string",
      "surface": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "plant_save_result": {
    "description": "Records the Fernly plant save result product milestone.",
    "trigger": "Emitted by the existing plant save result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "plant_update_result": {
    "description": "Records the Fernly plant update result product milestone.",
    "trigger": "Emitted by the existing plant update result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "changed_photo": "boolean",
      "reason": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "premium_cta": {
    "description": "Records the Fernly premium cta product milestone.",
    "trigger": "Emitted by the existing premium cta application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "purchase_result": {
    "description": "Records the Fernly purchase result product milestone.",
    "trigger": "Emitted by the existing purchase result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "plan": "string",
      "result": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "high",
    "partnerPostbackEligible": true
  },
  "purchase_start": {
    "description": "Records the Fernly purchase start product milestone.",
    "trigger": "Emitted by the existing purchase start application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "plan": "string",
      "source": "string",
      "trial_eligible": "boolean"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "appsFlyerAlias": "af_initiated_checkout",
    "conversionPriority": "high",
    "partnerPostbackEligible": true
  },
  "restore_result": {
    "description": "Records the Fernly restore result product milestone.",
    "trigger": "Emitted by the existing restore result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "result": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "restore_start": {
    "description": "Records the Fernly restore start product milestone.",
    "trigger": "Emitted by the existing restore start application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "scan_again": {
    "description": "Records the Fernly scan again product milestone.",
    "trigger": "Emitted by the existing scan again application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "from_step": "string",
      "mode": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "scan_mode_change": {
    "description": "Records the Fernly scan mode change product milestone.",
    "trigger": "Emitted by the existing scan mode change application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "from_mode": "string",
      "source": "string",
      "to_mode": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "scan_submit": {
    "description": "Records the Fernly scan submit product milestone.",
    "trigger": "Emitted by the existing scan submit application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "has_plant_context": "boolean",
      "mode": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "sign_in_cancel": {
    "description": "Records the Fernly sign in cancel product milestone.",
    "trigger": "Emitted by the existing sign in cancel application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "provider": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "sign_in_failure": {
    "description": "Records the Fernly sign in failure product milestone.",
    "trigger": "Emitted by the existing sign in failure application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "provider": "string",
      "reason": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "permanent_account_created": {
    "description": "Records the Fernly permanent account created product milestone.",
    "trigger": "Emitted by the existing permanent account created application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "provider": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "appsFlyerAlias": "af_complete_registration",
    "conversionPriority": "high",
    "partnerPostbackEligible": true
  },
  "returning_sign_in": {
    "description": "Records the Fernly returning sign in product milestone.",
    "trigger": "Emitted by the existing returning sign in application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "provider": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "appsFlyerAlias": "af_login",
    "conversionPriority": "high",
    "partnerPostbackEligible": true
  },
  "sign_in_result": {
    "description": "Records the Fernly sign in result product milestone.",
    "trigger": "Emitted by the existing sign in result application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "provider": "string",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "sign_in_tap": {
    "description": "Records the Fernly sign in tap product milestone.",
    "trigger": "Emitted by the existing sign in tap application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "provider": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "sign_out": {
    "description": "Records the Fernly sign out product milestone.",
    "trigger": "Emitted by the existing sign out application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "task_interval_update": {
    "description": "Records the Fernly task interval update product milestone.",
    "trigger": "Emitted by the existing task interval update application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "interval_days": "number",
      "reason": "string",
      "result": "string",
      "task_type": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "task_toggle": {
    "description": "Records the Fernly task toggle product milestone.",
    "trigger": "Emitted by the existing task toggle application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "enabled": "boolean",
      "reason": "string",
      "result": "string",
      "task_type": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "today_task_complete": {
    "description": "Records the Fernly today task complete product milestone.",
    "trigger": "Emitted by the existing today task complete application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string",
      "source": "string",
      "task_type": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "ui_tap": {
    "description": "Records the Fernly ui tap product milestone.",
    "trigger": "Emitted by the existing ui tap application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "control_name": "string",
      "reason": "string",
      "source": "string",
      "surface": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "weather_location_remove": {
    "description": "Records the Fernly weather location remove product milestone.",
    "trigger": "Emitted by the existing weather location remove application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "weather_location_set": {
    "description": "Records the Fernly weather location set product milestone.",
    "trigger": "Emitted by the existing weather location set application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "reason": "string",
      "result": "string",
      "source": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  },
  "weather_tip_action": {
    "description": "Records the Fernly weather tip action product milestone.",
    "trigger": "Emitted by the existing weather tip action application flow.",
    "semantics": "Result and reason parameters distinguish successful, cancelled, and failed outcomes when applicable.",
    "parameters": {
      "action_kind": "string",
      "days": "number",
      "result": "string"
    },
    "privacy": "product_analytics",
    "routes": {
      "appsFlyer": true,
      "firebase": true
    },
    "conversionPriority": "none",
    "partnerPostbackEligible": false
  }
} as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
export type AnalyticsTapName = (typeof ANALYTICS_TAPS)[keyof typeof ANALYTICS_TAPS];
export type AnalyticsUserPropertyKey = (typeof ANALYTICS_USER_PROPERTY_KEYS)[number];

export type AnalyticsEventParamsByName = {
  "account_delete_prompt": {
    "source"?: string;
  };
  "account_delete_result": {
    "reason"?: string;
    "result"?: string;
  };
  "alternate_selected": {
    "alternate_rank"?: number;
    "selected"?: boolean;
  };
  "camera_permission_result": {
    "result"?: string;
    "source"?: string;
  };
  "care_log_result": {
    "reason"?: string;
    "result"?: string;
    "type"?: string;
  };
  "care_reminder_toggle": {
    "enabled"?: boolean;
    "result"?: string;
    "source"?: string;
  };
  "diagnose_result": {
    "reason"?: string;
    "result"?: string;
    "stage"?: string;
  };
  "diagnosis_attach_select": {
    "source"?: string;
  };
  "diagnosis_expand": {
    "expanded"?: boolean;
  };
  "diagnosis_save_result": {
    "attached_to_plant"?: boolean;
    "reason"?: string;
    "result"?: string;
    "target"?: string;
  };
  "deep_link_open": {
    "deferred"?: boolean;
    "destination"?: string;
    "result"?: string;
  };
  "first_plant_saved": {
    "source"?: string;
  };
  "free_limit_hit": {
    "mode"?: string;
    "reason"?: string;
    "stage"?: string;
  };
  "frost_alert_toggle": {
    "enabled"?: boolean;
    "result"?: string;
  };
  "growth_photo_add": {
    "reason"?: string;
    "result"?: string;
    "source"?: string;
  };
  "identify_result": {
    "has_species_profile"?: boolean;
    "reason"?: string;
    "result"?: string;
  };
  "legal_link_tap": {
    "surface"?: string;
    "target"?: string;
  };
  "library_permission_result": {
    "result"?: string;
    "source"?: string;
  };
  "manage_subscription_link": {
    "source"?: string;
  };
  "offer_code_redemption": {
    "result"?: string;
    "source"?: string;
  };
  "onboarding_complete": {
    "method"?: string;
  };
  "onboarding_skip": {

  };
  "notification_open": {
    "destination"?: string;
    "source"?: string;
  };
  "paywall_view": {
    "premium_status"?: string;
    "source"?: string;
  };
  "photo_capture": {
    "mode"?: string;
    "reason"?: string;
    "result"?: string;
  };
  "photo_pick": {
    "mode"?: string;
    "reason"?: string;
    "result"?: string;
  };
  "plan_select": {
    "plan"?: string;
    "source"?: string;
  };
  "plant_delete_prompt": {
    "source"?: string;
  };
  "plant_delete_result": {
    "reason"?: string;
    "result"?: string;
  };
  "plant_photo_replacement": {
    "reason"?: string;
    "result"?: string;
    "source"?: string;
    "surface"?: string;
  };
  "plant_save_result": {
    "reason"?: string;
    "result"?: string;
  };
  "plant_update_result": {
    "changed_photo"?: boolean;
    "reason"?: string;
    "result"?: string;
  };
  "premium_cta": {
    "reason"?: string;
    "source"?: string;
  };
  "purchase_result": {
    "plan"?: string;
    "result"?: string;
    "source"?: string;
  };
  "purchase_start": {
    "plan"?: string;
    "source"?: string;
    "trial_eligible"?: boolean;
  };
  "restore_result": {
    "result"?: string;
    "source"?: string;
  };
  "restore_start": {
    "source"?: string;
  };
  "scan_again": {
    "from_step"?: string;
    "mode"?: string;
  };
  "scan_mode_change": {
    "from_mode"?: string;
    "source"?: string;
    "to_mode"?: string;
  };
  "scan_submit": {
    "has_plant_context"?: boolean;
    "mode"?: string;
  };
  "sign_in_cancel": {
    "provider"?: string;
  };
  "sign_in_failure": {
    "provider"?: string;
    "reason"?: string;
  };
  "permanent_account_created": {
    "provider"?: string;
  };
  "returning_sign_in": {
    "provider"?: string;
  };
  "sign_in_result": {
    "provider"?: string;
    "result"?: string;
  };
  "sign_in_tap": {
    "provider"?: string;
  };
  "sign_out": {
    "result"?: string;
  };
  "task_interval_update": {
    "interval_days"?: number;
    "reason"?: string;
    "result"?: string;
    "task_type"?: string;
  };
  "task_toggle": {
    "enabled"?: boolean;
    "reason"?: string;
    "result"?: string;
    "task_type"?: string;
  };
  "today_task_complete": {
    "reason"?: string;
    "result"?: string;
    "source"?: string;
    "task_type"?: string;
  };
  "ui_tap": {
    "control_name"?: string;
    "reason"?: string;
    "source"?: string;
    "surface"?: string;
  };
  "weather_location_remove": {
    "result"?: string;
  };
  "weather_location_set": {
    "reason"?: string;
    "result"?: string;
    "source"?: string;
  };
  "weather_tip_action": {
    "action_kind"?: string;
    "days"?: number;
    "result"?: string;
  };
};
export type AnalyticsParamsFor<Name extends AnalyticsEventName> = AnalyticsEventParamsByName[Name];
