import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  analyticsManifest,
  analyticsTapManifest,
  analyticsUserPropertyManifest
} from "../analytics/manifest";
import { generatedOutputMatches } from "./generatedOutput";

const root = path.resolve(__dirname, "..");
const outputs = new Map<string, string>([
  [
    "lib/analytics/events.generated.ts",
    renderTypeScript()
  ],
  ["docs/analytics-events.md", renderMarkdown()],
  ["docs/analytics-events.csv", renderCsv()]
]);
void main();

async function main() {
  const check = process.argv.includes("--check");
  let stale = false;

  for (const [relativePath, content] of outputs) {
    const target = path.join(root, relativePath);

    if (check) {
      const current = await readFile(target, "utf8").catch(() => "");

      if (!generatedOutputMatches(current, content)) {
        stale = true;
        console.error(`Generated analytics output is stale: ${relativePath}`);
      }
    } else {
      await writeFile(target, content, "utf8");
      console.log(`Generated ${relativePath}`);
    }
  }

  if (stale) {
    process.exitCode = 1;
  }
}

function renderTypeScript() {
  const events = Object.fromEntries(
    analyticsManifest.map((entry) => [entry.key, entry.name])
  );
  const definitions = Object.fromEntries(
    analyticsManifest.map((entry) => [
      entry.name,
      {
        description: entry.description,
        trigger: entry.trigger,
        semantics: entry.semantics,
        parameters: entry.parameters,
        privacy: entry.privacy,
        routes: {
          appsFlyer: entry.appsFlyer,
          firebase: entry.firebase
        },
        ...(entry.appsFlyerAlias
          ? { appsFlyerAlias: entry.appsFlyerAlias }
          : {}),
        ...(entry.aliasWhen ? { aliasWhen: entry.aliasWhen } : {}),
        conversionPriority: entry.conversionPriority,
        partnerPostbackEligible: entry.partnerPostbackEligible
      }
    ])
  );
  const parameterTypes = analyticsManifest
    .map((entry) => {
      const fields = Object.entries(entry.parameters)
        .map(([name, type]) => `    ${JSON.stringify(name)}?: ${type};`)
        .join("\n");

      return `  ${JSON.stringify(entry.name)}: {\n${fields}\n  };`;
    })
    .join("\n");

  return `// Generated by scripts/generate-analytics.ts. Do not edit by hand.\n\n` +
    `export const ANALYTICS_EVENTS = ${JSON.stringify(events, null, 2)} as const;\n\n` +
    `export const ANALYTICS_TAPS = ${JSON.stringify(analyticsTapManifest, null, 2)} as const;\n\n` +
    `export const ANALYTICS_USER_PROPERTY_KEYS = ${JSON.stringify(analyticsUserPropertyManifest, null, 2)} as const;\n\n` +
    `export const GENERATED_EVENT_DEFINITIONS = ${JSON.stringify(definitions, null, 2)} as const;\n\n` +
    `export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];\n` +
    `export type AnalyticsTapName = (typeof ANALYTICS_TAPS)[keyof typeof ANALYTICS_TAPS];\n` +
    `export type AnalyticsUserPropertyKey = (typeof ANALYTICS_USER_PROPERTY_KEYS)[number];\n\n` +
    `export type AnalyticsEventParamsByName = {\n${parameterTypes}\n};\n` +
    `export type AnalyticsParamsFor<Name extends AnalyticsEventName> = AnalyticsEventParamsByName[Name];\n`;
}

function renderMarkdown() {
  const rows = analyticsManifest.map(
    (entry) =>
      `| \`${entry.name}\` | ${entry.description} | ${entry.trigger} | ${formatParameters(entry.parameters)} | ${entry.appsFlyerAlias ? `\`${entry.appsFlyerAlias}\`` : "same name"} | ${entry.conversionPriority} | ${entry.partnerPostbackEligible ? "yes" : "no"} |`
  );

  return `# Fernly Analytics Event Catalog\n\n` +
    `Generated from \`analytics/manifest.ts\`. RevenueCat is the only source of subscription lifecycle revenue; these client events contain funnel status only.\n\n` +
    `| Event | Description | Trigger | Allowed parameters | AppsFlyer name | Priority | Partner postback |\n` +
    `|---|---|---|---|---|---|---|\n${rows.join("\n")}\n`;
}

function renderCsv() {
  const headers = [
    "event",
    "description",
    "trigger",
    "semantics",
    "parameters",
    "privacy",
    "firebase",
    "appsflyer",
    "appsflyer_alias",
    "conversion_priority",
    "partner_postback_eligible"
  ];
  const rows = analyticsManifest.map((entry) => [
    entry.name,
    entry.description,
    entry.trigger,
    entry.semantics,
    formatParameters(entry.parameters),
    entry.privacy,
    String(entry.firebase),
    String(entry.appsFlyer),
    entry.appsFlyerAlias ?? entry.name,
    entry.conversionPriority,
    String(entry.partnerPostbackEligible)
  ]);

  return `${headers.map(csv).join(",")}\n${rows
    .map((row) => row.map(csv).join(","))
    .join("\n")}\n`;
}

function formatParameters(parameters: Record<string, string>) {
  const entries = Object.entries(parameters);

  return entries.length
    ? entries.map(([name, type]) => `${name}:${type}`).join("; ")
    : "none";
}

function csv(value: string) {
  return `"${value.replaceAll('"', '""')}"`;
}
